// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
// Generated by scripts/gen_cgra_if.py
// ============================================================================

`timescale 1ns/1ps

interface cgra_if (input logic clk);
    import cgra_pkg::*;

    // DUT port signals
    logic [0:0] reset;
    logic [0:0] recv_waddr__en [0:63];
    logic [2:0] recv_waddr__msg [0:63];
    logic [0:0] recv_waddr__rdy [0:63];
    logic [0:0] recv_wopt__en [0:63];
    CGRAConfig_6_4_10_12 recv_wopt__msg [0:63];
    logic [0:0] recv_wopt__rdy [0:63];

    // TB-only post-run controls
    logic dump_enable;
    logic dump_const_mem_enable;
    logic dump_ctrl_mem_enable;
    logic dump_data_mem_enable;
    int unsigned post_launch_wait_cycles;
    int unsigned expected_result_count;
    logic [31:0] expected_result_payloads [0:15];

    clocking driver_cb @(posedge clk);
        default input #1step output #1;
        output reset;
        output recv_waddr__en;
        output recv_waddr__msg;
        input  recv_waddr__rdy;
        output recv_wopt__en;
        output recv_wopt__msg;
        input  recv_wopt__rdy;
    endclocking

    clocking monitor_cb @(posedge clk);
        default input #1step;
        input reset;
        input recv_waddr__en;
        input recv_waddr__msg;
        input recv_waddr__rdy;
        input recv_wopt__en;
        input recv_wopt__msg;
        input recv_wopt__rdy;
    endclocking

    modport driver_mp  (clocking driver_cb,  input clk);
    modport monitor_mp (clocking monitor_cb, input clk);
endinterface : cgra_if
