# =============================================================================
# rtl.f - AUTO-GENERATED by Makefile target 'gen_filelists'
# Compilation order:
# - packages
# - modules
# - top
# =============================================================================

# ---------------------------------------------------------------------------
# Packages
# ---------------------------------------------------------------------------
src/rtl/pkg/cgra_pkg.sv

# ---------------------------------------------------------------------------
# Modules (alphabetical)
# ---------------------------------------------------------------------------
src/rtl/modules/AdderRTL__cf54288ae5eea774.sv
src/rtl/modules/BranchRTL__cf54288ae5eea774.sv
src/rtl/modules/ChannelRTL__DataType_CGRAData_32_1_1__latency_1.sv
src/rtl/modules/CompRTL__cf54288ae5eea774.sv
src/rtl/modules/ConstQueueRTL__2f4560623c67a554.sv
src/rtl/modules/CrossbarRTL__d1ac2c47b6d2acea.sv
src/rtl/modules/CtrlMemRTL__a45182edfad853a0.sv
src/rtl/modules/DataMemRTL__16e627fe25c0c2a2.sv
src/rtl/modules/FlexibleFuRTL__9cb301226ddb80f2.sv
src/rtl/modules/LogicRTL__cf54288ae5eea774.sv
src/rtl/modules/MemUnitRTL__cf54288ae5eea774.sv
src/rtl/modules/MulRTL__cf54288ae5eea774.sv
src/rtl/modules/NormalQueueCtrlRTL__num_entries_2.sv
src/rtl/modules/NormalQueueDpathRTL__EntryType_CGRAData_1_1__num_entries_2.sv
src/rtl/modules/NormalQueueDpathRTL__EntryType_CGRAData_32_1_1__num_entries_2.sv
src/rtl/modules/NormalQueueRTL__EntryType_CGRAData_1_1__num_entries_2.sv
src/rtl/modules/NormalQueueRTL__EntryType_CGRAData_32_1_1__num_entries_2.sv
src/rtl/modules/PhiRTL__cf54288ae5eea774.sv
src/rtl/modules/RegisterFile__4c93ecd593d406ca.sv
src/rtl/modules/RegisterFile__b2651f5e70154f41.sv
src/rtl/modules/RegisterFile__c3c6554272304d54.sv
src/rtl/modules/RegisterFile__e355018d318c7c45.sv
src/rtl/modules/RegisterRTL__DataType_CGRAData_1_1__latency_1.sv
src/rtl/modules/RetRTL__cf54288ae5eea774.sv
src/rtl/modules/SelRTL__cf54288ae5eea774.sv
src/rtl/modules/SeqMulAdderRTL__cf54288ae5eea774.sv
src/rtl/modules/ShifterRTL__cf54288ae5eea774.sv
src/rtl/modules/TileRTL__627d9ddbf28d8dc8.sv

# ---------------------------------------------------------------------------
# RTL top
# ---------------------------------------------------------------------------
src/rtl/top/CgraTemplateRTL.sv
