# =============================================================================
# val.f - AUTO-GENERATED by Makefile target 'gen_filelists'
# =============================================================================

# +incdir for `include resolution
+incdir+src/val/agents
+incdir+src/val/coverage
+incdir+src/val/drivers
+incdir+src/val/env
+incdir+src/val/monitors
+incdir+src/val/properties
+incdir+src/val/scoreboards
+incdir+src/val/sequences
+incdir+src/val/tests
+incdir+src/gen

# UVM package(s)
src/val/pkg/cgra_uvm_pkg.sv

# Interface(s)
src/val/intf/cgra_if.sv

# Assertion module(s)
src/val/assertions/cgra_assertions.sv

# Testbench top(s)
src/val/tb/cgra_tb_top.sv
