"""
Auto-generate src/val/intf/cgra_if.sv from the top RTL module ports.
"""

import argparse
import re
import sys
from pathlib import Path


def _parse_top_module_name(top_text: str) -> str:
    alias_match = re.search(r"`define\s+CgraTemplateRTL\s+(\w+)", top_text)
    if alias_match:
        return alias_match.group(1)

    module_match = re.search(r"\bmodule\s+(\w+)", top_text)
    if module_match:
        return module_match.group(1)

    raise ValueError("Could not determine top module name from top RTL file")


def _extract_ports(top_text: str, module_name: str) -> list[tuple[str, str, str, str]]:
    header_match = re.search(
        rf"\bmodule\s+{re.escape(module_name)}\s*(?:import\s+\w+::\*;\s*)?\((.*?)\)\s*;",
        top_text,
        re.DOTALL,
    )
    if not header_match:
        raise ValueError(f"Could not parse module header for '{module_name}'")

    port_block = header_match.group(1)
    raw_ports = [p.strip() for p in port_block.split(",") if p.strip()]

    ports: list[tuple[str, str, str, str]] = []
    for raw in raw_ports:
        clean = re.sub(r"//.*", "", raw).strip()
        clean = re.sub(r"\s+", " ", clean)
        if not clean:
            continue

        port_match = re.match(
            r"^(input|output)\s+(.+?)\s+([A-Za-z_]\w*)(\s*(?:\[[^\]]+\]\s*)*)$",
            clean,
        )
        if not port_match:
            raise ValueError(f"Unsupported port declaration: '{clean}'")

        direction, data_type, name, unpacked_dims = port_match.groups()
        ports.append((direction, data_type.strip(), name, unpacked_dims.strip()))

    return ports


def _render_cgra_if(ports: list[tuple[str, str, str, str]]) -> str:
    signals = [p for p in ports if p[2] != "clk"]

    lines: list[str] = []
    lines.extend(
        [
            "// ============================================================================",
            "// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.",
            "// Generated by scripts/gen_cgra_if.py",
            "// ============================================================================",
            "",
            "`timescale 1ns/1ps",
            "",
            "interface cgra_if (input logic clk);",
            "    import cgra_pkg::*;",
            "",
            "    // DUT port signals",
        ]
    )

    for _, data_type, name, unpacked in signals:
        suffix = f" {unpacked}" if unpacked else ""
        lines.append(f"    {data_type} {name}{suffix};")

    lines.extend(
        [
            "",
            "    // TB-only post-run controls",
            "    logic dump_enable;",
            "    logic dump_const_mem_enable;",
            "    logic dump_ctrl_mem_enable;",
            "    logic dump_data_mem_enable;",
            "    int unsigned post_launch_wait_cycles;",
            "    int unsigned expected_result_count;",
            "    logic [31:0] expected_result_payloads [0:15];",
            "",
            "    clocking driver_cb @(posedge clk);",
            "        default input #1step output #1;",
        ]
    )

    for direction, _, name, _ in signals:
        if direction == "input":
            lines.append(f"        output {name};")
        else:
            lines.append(f"        input  {name};")

    lines.extend(
        [
            "    endclocking",
            "",
            "    clocking monitor_cb @(posedge clk);",
            "        default input #1step;",
        ]
    )

    for _, _, name, _ in signals:
        lines.append(f"        input {name};")

    lines.extend(
        [
            "    endclocking",
            "",
            "    modport driver_mp  (clocking driver_cb,  input clk);",
            "    modport monitor_mp (clocking monitor_cb, input clk);",
            "endinterface : cgra_if",
            "",
        ]
    )

    return "\n".join(lines)


def generate_cgra_if(top_path: Path, out_path: Path) -> None:
    top_text = top_path.read_text(encoding="utf-8")
    top_module_name = _parse_top_module_name(top_text)
    ports = _extract_ports(top_text, top_module_name)
    interface_text = _render_cgra_if(ports)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(interface_text, encoding="utf-8")
    print(f"Created: {out_path}")


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="gen_cgra_if",
        description="Generate src/val/intf/cgra_if.sv from the top RTL module ports.",
    )
    parser.add_argument(
        "--top",
        default=Path("src/rtl/top/CgraTemplateRTL.sv"),
        type=Path,
        help="Path to top RTL module file (default: src/rtl/top/CgraTemplateRTL.sv)",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=Path("src/val/intf/cgra_if.sv"),
        type=Path,
        help="Output interface path (default: src/val/intf/cgra_if.sv)",
    )
    return parser


def main() -> None:
    args = _build_parser().parse_args()

    if not args.top.exists() or not args.top.is_file():
        print(f"Error: top file '{args.top}' not found or not a regular file.", file=sys.stderr)
        sys.exit(1)

    generate_cgra_if(args.top, args.output)


if __name__ == "__main__":
    main()
