"""rtl_to_opcodes.py

Scan RTL module source files for opcode localparams and emit:

  - spec/opcodes.json           (opcode name → integer value, sorted)
  - src/gen/cgra_opcodes.svh    (SystemVerilog ``define macros, 6-bit width)

Pattern matched in every .sv file under --rtl-dir::

    localparam logic [5:0] __const__OPT_<NAME> = 6'd<VALUE>;

Usage::

    python scripts/rtl_to_opcodes.py
    python scripts/rtl_to_opcodes.py --rtl-dir src/rtl
    python scripts/rtl_to_opcodes.py --rtl-dir src/rtl \\
        -o spec/opcodes.json --svh src/gen/cgra_opcodes.svh
"""

import argparse
import json
import re
import sys
from pathlib import Path

_LOCALPARAM_RE = re.compile(
    r"\blocalparam\s+logic\s*\[5:0\]\s+__const__(OPT_\w+)\s*=\s*6'd(\d+)\s*;"
)


def _scan_opcodes(rtl_dir: Path) -> dict[str, int]:
    """Scan all .sv files under *rtl_dir* and collect unique OPT_* → value pairs.

    Files are visited in sorted order so results are deterministic.  When the
    same name appears with conflicting values a warning is printed to stderr;
    the last definition wins.
    """
    opcodes: dict[str, int] = {}
    for sv_file in sorted(rtl_dir.rglob("*.sv")):
        text = sv_file.read_text(encoding="utf-8", errors="replace")
        for m in _LOCALPARAM_RE.finditer(text):
            name, value = m.group(1), int(m.group(2))
            if name in opcodes and opcodes[name] != value:
                print(
                    f"[WARNING] {name} redefined: {opcodes[name]} → {value}"
                    f" (in {sv_file})",
                    file=sys.stderr,
                )
            opcodes[name] = value
    return opcodes


def _write_json(opcodes: dict[str, int], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(dict(sorted(opcodes.items())), indent=2) + "\n",
        encoding="utf-8",
    )


def _write_svh(opcodes: dict[str, int], output: Path) -> None:
    lines = [
        "`ifndef CGRA_OPCODE_DEFINES_SVH",
        "`define CGRA_OPCODE_DEFINES_SVH",
        "",
        "// Auto-generated by scripts/rtl_to_opcodes.py",
        "// Do not edit manually — re-run 'make gen_opcodes'.",
        "",
    ]
    for name in sorted(opcodes):
        lines.append(f"`define {name} 6'd{opcodes[name]}")
    lines.extend(["", "`endif // CGRA_OPCODE_DEFINES_SVH", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate opcodes.json and cgra_opcodes.svh from RTL localparams.",
    )
    parser.add_argument(
        "--rtl-dir",
        default="src/rtl",
        help="Root directory to search for .sv RTL files (default: src/rtl)",
    )
    parser.add_argument(
        "-o", "--output",
        default="spec/opcodes.json",
        help="Path to write opcodes.json (default: spec/opcodes.json)",
    )
    parser.add_argument(
        "--svh",
        default="src/gen/cgra_opcodes.svh",
        help="Path to write cgra_opcodes.svh (default: src/gen/cgra_opcodes.svh)",
    )
    args = parser.parse_args()

    rtl_dir = Path(args.rtl_dir)
    if not rtl_dir.is_dir():
        sys.exit(f"[ERROR] RTL directory not found: {rtl_dir}")

    opcodes = _scan_opcodes(rtl_dir)
    if not opcodes:
        sys.exit(f"[ERROR] No OPT_* localparams found under {rtl_dir}")

    json_path = Path(args.output)
    svh_path  = Path(args.svh)

    _write_json(opcodes, json_path)
    _write_svh(opcodes, svh_path)

    print(f"[INFO] Wrote {len(opcodes)} opcodes → {json_path}")
    print(f"[INFO] Wrote svh header    → {svh_path}")


if __name__ == "__main__":
    main()
